name: Deploy Docker Fullstack App

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        echo "🚀 Starting deployment..."

        cd ~

        if [ ! -d "docker-fullstack-app" ]; then
          git clone https://github.com/altafali309/docker-fullstack-app.git
        fi

        cd docker-fullstack-app

        git pull origin main

        docker-compose down
        docker-compose up -d --build

        echo "✅ Deployment completed!"

